version: '3'

services:
  rancher:
    image: rancher/rancher:stable
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - rancher-data:/var/lib/rancher
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rancher.entrypoints=https"
      - "traefik.http.routers.rancher.rule=Host(`rancher.odoocast.com`)"
      - "traefik.http.services.rancher.loadbalancer.server.port=80"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=Host(`nginx.odoocast.com`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  harbor:
    image: goharbor/harbor-core:v2.2.2
    restart: unless-stopped
    ports:
      - "8443:443"
    volumes:
      - harbor-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.harbor.entrypoints=https"
      - "traefik.http.routers.harbor.rule=Host(`harbor.odoocast.com`)"
      - "traefik.http.services.harbor.loadbalancer.server.port=443"

volumes:
  rancher-data:
  harbor-data:
